### ISSUE TITLE
所以 Docker postgresql container 的 database 資料都存在哪裡呀？

### ISSUE THREAD

**Issue by kuihao** [twtrubiks/odoo-development-environment-tutorial#3]
依照我爬文的理解，Docker-compose.yml 的 volumes 是保存 container 資料的路徑
volumes 是寫「odoo-db-data:/var/lib/postgresql/data/pgdata」可是我去看 /var/lib 並沒有找到 postgresql 資料夾耶？
反而 database 的資料好像是出現在 odoo.conf 所定義的 「data_dir = /home/twtrubiks/Downloads/odoo-git/odoo-data」裡面？

這就竟是怎一回事呀？難道 odoo 有程式負責把 Docker volumes 路徑重新 mapping 到 odoo.conf 的 data_dir 裡面嗎？
想請大大補充這個部份的運作原理

**Comment by twtrubiks** [comment]
volumes 是寫「odoo-db-data:/var/lib/postgresql/data/pgdata」可是我去看 /var/lib 並沒有找到 ostgresql 資料夾耶？
-> 是有 postgresql 資料夾 的, 你要進去 "容器" 內.

**Comment by kuihao** [comment]
了解 我再試試看
