### ISSUE TITLE
pip install 安裝依賴的時候有報錯pg_config executable not found

### ISSUE THREAD

**Issue by ft-ttbl** [twtrubiks/odoo-development-environment-tutorial#4]
我的device是Mac mini i5
源碼安裝odoo 15.0
在虛擬環境下安裝依賴的時候報了這個錯：
![Screen Shot 2023-01-06 at 11 51 17 AM](https://user-images.githubusercontent.com/110932236/211088755-fdeeed76-81d9-40d1-aca8-ccf898733e51.png)
這個是說要把pg_config的文件路徑加到$path裡面嗎？但是package都還沒安裝好哪來的路徑呢？

**Comment by twtrubiks** [comment]
參考一下文章的
可能出現的錯誤三,
有時候 psycopg2 會安裝失敗(odoo15), 建議可以改安裝 psycopg2-binary.
```cmd
pip3 install psycopg2-binary
```

**Comment by gongmin00** [comment]
对，我也是这个问题，改用psycopg2-binary就可以。
